=== crd-hub/crdhub/public/ui.k8s.appscode.com/resourceeditors/v1alpha1/openapiv3_schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "apiVersion": {
      "description": "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources",
      "type": "string",
      "enum": [
        "ui.k8s.appscode.com/v1alpha1"
      ]
    },
    "kind": {
      "description": "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds",
      "type": "string",
      "enum": [
        "ResourceEditor"
      ]
    },
    "metadata": {
      "type": "object",
      "properties": {
        "annotations": {
          "description": "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "labels": {
          "description": "Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "name": {
          "description": "Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names",
          "type": "string"
        }
      }
    },
    "spec": {
      "type": "object",
      "required": [
        "resource"
      ],
      "properties": {
        "icons": {
          "description": "Icons is an optional list of icons for an application. Icon information includes the source, size,\nand mime type.",
          "type": "array",
          "items": {
            "description": "ImageSpec contains information about an image used as an icon.",
            "type": "object",
            "required": [
              "src"
            ],
            "properties": {
              "size": {
                "description": "(optional) The size of the image in pixels (e.g., 25x25).",
                "type": "string"
              },
              "src": {
                "description": "The source for image represented as either an absolute URL to the image or a Data URL containing\nthe image. Data URLs are defined in RFC 2397.",
                "type": "string"
              },
              "type": {
                "description": "(optional) The mine type of the image (e.g., \"image/png\").",
                "type": "string"
              }
            }
          }
        },
        "installer": {
          "type": "object",
          "properties": {
            "chart": {
              "description": "ChartSourceRef references to a single version of a Chart",
              "type": "object",
              "required": [
                "name",
                "sourceRef",
                "version"
              ],
              "properties": {
                "name": {
                  "type": "string"
                },
                "sourceRef": {
                  "description": "TypedObjectReference represents a typed namespaced object.",
                  "type": "object",
                  "required": [
                    "name"
                  ],
                  "properties": {
                    "apiGroup": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "description": "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
                      "type": "string"
                    },
                    "namespace": {
                      "description": "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/",
                      "type": "string"
                    }
                  }
                },
                "version": {
                  "type": "string"
                }
              }
            },
            "planID": {
              "type": "string"
            },
            "productID": {
              "type": "string"
            }
          }
        },
        "resource": {
          "description": "ResourceID identifies a resource",
          "type": "object",
          "required": [
            "group"
          ],
          "properties": {
            "group": {
              "type": "string"
            },
            "kind": {
              "description": "Kind is the serialized kind of the resource.  It is normally CamelCase and singular.",
              "type": "string"
            },
            "name": {
              "description": "Name is the plural name of the resource to serve.  It must match the name of the CustomResourceDefinition-registration\ntoo: plural.group and it must be all lowercase.",
              "type": "string"
            },
            "scope": {
              "description": "ResourceScope is an enum defining the different scopes available to a custom resource",
              "type": "string"
            },
            "version": {
              "type": "string"
            }
          }
        },
        "ui": {
          "type": "object",
          "required": [
            "enforceQuota"
          ],
          "properties": {
            "actions": {
              "type": "array",
              "items": {
                "type": "object",
                "required": [
                  "items"
                ],
                "properties": {
                  "description": {
                    "type": "string"
                  },
                  "icon": {
                    "type": "string"
                  },
                  "items": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "required": [
                        "enforceQuota",
                        "flow",
                        "operationId"
                      ],
                      "properties": {
                        "description": {
                          "type": "string"
                        },
                        "disabledTemplate": {
                          "type": "string"
                        },
                        "editor": {
                          "description": "ChartSourceRef references to a single version of a Chart",
                          "type": "object",
                          "required": [
                            "name",
                            "sourceRef",
                            "version"
                          ],
                          "properties": {
                            "name": {
                              "type": "string"
                            },
                            "sourceRef": {
                              "description": "TypedObjectReference represents a typed namespaced object.",
                              "type": "object",
                              "required": [
                                "name"
                              ],
                              "properties": {
                                "apiGroup": {
                                  "type": "string"
                                },
                                "kind": {
                                  "type": "string"
                                },
                                "name": {
                                  "description": "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
                                  "type": "string"
                                },
                                "namespace": {
                                  "description": "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/",
                                  "type": "string"
                                }
                              }
                            },
                            "version": {
                              "type": "string"
                            }
                          }
                        },
                        "enforceQuota": {
                          "type": "boolean"
                        },
                        "flow": {
                          "type": "string"
                        },
                        "icon": {
                          "type": "string"
                        },
                        "icons": {
                          "type": "array",
                          "items": {
                            "description": "ImageSpec contains information about an image used as an icon.",
                            "type": "object",
                            "required": [
                              "src"
                            ],
                            "properties": {
                              "size": {
                                "description": "(optional) The size of the image in pixels (e.g., 25x25).",
                                "type": "string"
                              },
                              "src": {
                                "description": "The source for image represented as either an absolute URL to the image or a Data URL containing\nthe image. Data URLs are defined in RFC 2397.",
                                "type": "string"
                              },
                              "type": {
                                "description": "(optional) The mine type of the image (e.g., \"image/png\").",
                                "type": "string"
                              }
                            }
                          }
                        },
                        "name": {
                          "type": "string"
                        },
                        "operationId": {
                          "type": "string"
                        },
                        "partOf": {
                          "type": "string"
                        }
                      }
                    }
                  },
                  "name": {
                    "type": "string"
                  }
                }
              }
            },
            "editor": {
              "description": "ChartSourceRef references to a single version of a Chart",
              "type": "object",
              "required": [
                "name",
                "sourceRef",
                "version"
              ],
              "properties": {
                "name": {
                  "type": "string"
                },
                "sourceRef": {
                  "description": "TypedObjectReference represents a typed namespaced object.",
                  "type": "object",
                  "required": [
                    "name"
                  ],
                  "properties": {
                    "apiGroup": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "description": "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
                      "type": "string"
                    },
                    "namespace": {
                      "description": "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/",
                      "type": "string"
                    }
                  }
                },
                "version": {
                  "type": "string"
                }
              }
            },
            "enforceQuota": {
              "type": "boolean"
            },
            "instanceLabelPaths": {
              "description": "app.kubernetes.io/instance label must be updated at these paths when refilling metadata",
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "options": {
              "description": "ChartSourceRef references to a single version of a Chart",
              "type": "object",
              "required": [
                "name",
                "sourceRef",
                "version"
              ],
              "properties": {
                "name": {
                  "type": "string"
                },
                "sourceRef": {
                  "description": "TypedObjectReference represents a typed namespaced object.",
                  "type": "object",
                  "required": [
                    "name"
                  ],
                  "properties": {
                    "apiGroup": {
                      "type": "string"
                    },
                    "kind": {
                      "type": "string"
                    },
                    "name": {
                      "description": "Name of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names",
                      "type": "string"
                    },
                    "namespace": {
                      "description": "Namespace of the referent.\nMore info: https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/",
                      "type": "string"
                    }
                  }
                },
                "version": {
                  "type": "string"
                }
              }
            }
          }
        },
        "variants": {
          "description": "Kind == VendorChartPreset | ClusterChartPreset",
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "name"
            ],
            "properties": {
              "description": {
                "type": "string"
              },
              "icons": {
                "description": "Icons is an optional list of icons for an application. Icon information includes the source, size,\nand mime type.",
                "type": "array",
                "items": {
                  "description": "ImageSpec contains information about an image used as an icon.",
                  "type": "object",
                  "required": [
                    "src"
                  ],
                  "properties": {
                    "size": {
                      "description": "(optional) The size of the image in pixels (e.g., 25x25).",
                      "type": "string"
                    },
                    "src": {
                      "description": "The source for image represented as either an absolute URL to the image or a Data URL containing\nthe image. Data URLs are defined in RFC 2397.",
                      "type": "string"
                    },
                    "type": {
                      "description": "(optional) The mine type of the image (e.g., \"image/png\").",
                      "type": "string"
                    }
                  }
                }
              },
              "name": {
                "type": "string"
              },
              "selector": {
                "description": "A label selector is a label query over a set of resources. The result of matchLabels and\nmatchExpressions are ANDed. An empty label selector matches all objects. A null\nlabel selector matches no objects.",
                "type": "object",
                "properties": {
                  "matchExpressions": {
                    "description": "matchExpressions is a list of label selector requirements. The requirements are ANDed.",
                    "type": "array",
                    "items": {
                      "description": "A label selector requirement is a selector that contains values, a key, and an operator that\nrelates the key and values.",
                      "type": "object",
                      "required": [
                        "key",
                        "operator"
                      ],
                      "properties": {
                        "key": {
                          "description": "key is the label key that the selector applies to.",
                          "type": "string"
                        },
                        "operator": {
                          "description": "operator represents a key's relationship to a set of values.\nValid operators are In, NotIn, Exists and DoesNotExist.",
                          "type": "string"
                        },
                        "values": {
                          "description": "values is an array of string values. If the operator is In or NotIn,\nthe values array must be non-empty. If the operator is Exists or DoesNotExist,\nthe values array must be empty. This array is replaced during a strategic\nmerge patch.",
                          "type": "array",
                          "items": {
                            "type": "string"
                          },
                          "x-kubernetes-list-type": "atomic"
                        }
                      }
                    },
                    "x-kubernetes-list-type": "atomic"
                  },
                  "matchLabels": {
                    "description": "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels\nmap is equivalent to an element of matchExpressions, whose key field is \"key\", the\noperator is \"In\", and the values array contains only \"value\". The requirements are ANDed.",
                    "type": "object",
                    "additionalProperties": {
                      "type": "string"
                    }
                  }
                },
                "x-kubernetes-map-type": "atomic"
              },
              "title": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}

=== crd-hub/crdhub/public/databoxedge.azure.upbound.io/devices/v1beta1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "databoxedge.azure.upbound.io-v1beta1-devices",
    "creationTimestamp": null,
    "labels": {
      "k8s.io/group": "databoxedge.azure.upbound.io",
      "k8s.io/kind": "Device",
      "k8s.io/resource": "devices",
      "k8s.io/version": "v1beta1"
    }
  },
  "spec": {
    "resource": {
      "group": "databoxedge.azure.upbound.io",
      "version": "v1beta1",
      "name": "devices",
      "kind": "Device",
      "scope": "Cluster"
    },
    "ui": {
      "editor": {
        "name": "databoxedgeazureupboundio-device-editor",
        "version": "v0.4.18",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "bytebuilders-ui"
        }
      },
      "enforceQuota": false
    }
  }
}

=== crd-hub/crdhub/public/storagecache.azure.upbound.io/hpccacheblobtargets/v1beta1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "storagecache.azure.upbound.io-v1beta1-hpccacheblobtargets",
    "creationTimestamp": null,
    "labels": {
      "k8s.io/group": "storagecache.azure.upbound.io",
      "k8s.io/kind": "HPCCacheBlobTarget",
      "k8s.io/resource": "hpccacheblobtargets",
      "k8s.io/version": "v1beta1"
    }
  },
  "spec": {
    "resource": {
      "group": "storagecache.azure.upbound.io",
      "version": "v1beta1",
      "name": "hpccacheblobtargets",
      "kind": "HPCCacheBlobTarget",
      "scope": "Cluster"
    },
    "ui": {
      "editor": {
        "name": "storagecacheazureupboundio-hpccacheblobtarget-editor",
        "version": "v0.4.18",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "bytebuilders-ui"
        }
      },
      "enforceQuota": false
    }
  }
}

=== crd-hub/crdhub/public/automation.azure.upbound.io/modules/v1beta1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "automation.azure.upbound.io-v1beta1-modules",
    "creationTimestamp": null,
    "labels": {
      "k8s.io/group": "automation.azure.upbound.io",
      "k8s.io/kind": "Module",
      "k8s.io/resource": "modules",
      "k8s.io/version": "v1beta1"
    }
  },
  "spec": {
    "resource": {
      "group": "automation.azure.upbound.io",
      "version": "v1beta1",
      "name": "modules",
      "kind": "Module",
      "scope": "Cluster"
    },
    "ui": {
      "editor": {
        "name": "automationazureupboundio-module-editor",
        "version": "v0.4.18",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "bytebuilders-ui"
        }
      },
      "enforceQuota": false
    }
  }
}

=== crd-hub/crdhub/public/keyspaces.aws.upbound.io/tables/v1beta1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "keyspaces.aws.upbound.io-v1beta1-tables",
    "creationTimestamp": null,
    "labels": {
      "k8s.io/group": "keyspaces.aws.upbound.io",
      "k8s.io/kind": "Table",
      "k8s.io/resource": "tables",
      "k8s.io/version": "v1beta1"
    }
  },
  "spec": {
    "resource": {
      "group": "keyspaces.aws.upbound.io",
      "version": "v1beta1",
      "name": "tables",
      "kind": "Table",
      "scope": "Cluster"
    },
    "ui": {
      "editor": {
        "name": "keyspacesawsupboundio-table-editor",
        "version": "v0.4.18",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "bytebuilders-ui"
        }
      },
      "enforceQuota": false
    }
  }
}

=== crd-hub/crdhub/public/mediastore.aws.upbound.io/containerpolicies/v1beta1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "mediastore.aws.upbound.io-v1beta1-containerpolicies",
    "creationTimestamp": null,
    "labels": {
      "k8s.io/group": "mediastore.aws.upbound.io",
      "k8s.io/kind": "ContainerPolicy",
      "k8s.io/resource": "containerpolicies",
      "k8s.io/version": "v1beta1"
    }
  },
  "spec": {
    "resource": {
      "group": "mediastore.aws.upbound.io",
      "version": "v1beta1",
      "name": "containerpolicies",
      "kind": "ContainerPolicy",
      "scope": "Cluster"
    },
    "ui": {
      "editor": {
        "name": "mediastoreawsupboundio-containerpolicy-editor",
        "version": "v0.4.18",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "bytebuilders-ui"
        }
      },
      "enforceQuota": false
    }
  }
}

=== crd-hub/crdhub/public/catalog.kubeware.dev/pgbouncerbindings/v1alpha1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "catalog.kubeware.dev-v1alpha1-pgbouncerbindings",
    "labels": {
      "k8s.io/group": "catalog.kubeware.dev",
      "k8s.io/kind": "PgBouncerBinding",
      "k8s.io/resource": "pgbouncerbindings",
      "k8s.io/version": "v1alpha1"
    }
  },
  "spec": {
    "resource": {
      "group": "catalog.kubeware.dev",
      "version": "v1alpha1",
      "name": "pgbouncerbindings",
      "kind": "PgBouncerBinding",
      "scope": "Namespaced"
    },
    "ui": {
      "editor": {
        "name": "catalogkubewaredev-pgbouncerbinding-editor",
        "version": "v0.30.0",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "appscode-charts-oci"
        }
      },
      "enforceQuota": false
    }
  }
}

=== crd-hub/crdhub/public/notification.toolkit.fluxcd.io/alerts/v1beta1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "notification.toolkit.fluxcd.io-v1beta1-alerts",
    "labels": {
      "k8s.io/group": "notification.toolkit.fluxcd.io",
      "k8s.io/kind": "Alert",
      "k8s.io/resource": "alerts",
      "k8s.io/version": "v1beta1"
    }
  },
  "spec": {
    "resource": {
      "group": "notification.toolkit.fluxcd.io",
      "version": "v1beta1",
      "name": "alerts",
      "kind": "Alert",
      "scope": "Namespaced"
    },
    "ui": {
      "editor": {
        "name": "notificationtoolkitfluxcdio-alert-editor",
        "version": "v0.30.0",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "appscode-charts-oci"
        }
      },
      "enforceQuota": false
    }
  }
}

=== crd-hub/crdhub/public/catalog.appscode.com/pgpoolbindings/v1alpha1/resourceeditor.json
{
  "kind": "ResourceEditor",
  "apiVersion": "ui.k8s.appscode.com/v1alpha1",
  "metadata": {
    "name": "catalog.appscode.com-v1alpha1-pgpoolbindings",
    "labels": {
      "k8s.io/group": "catalog.appscode.com",
      "k8s.io/kind": "PgpoolBinding",
      "k8s.io/resource": "pgpoolbindings",
      "k8s.io/version": "v1alpha1"
    }
  },
  "spec": {
    "resource": {
      "group": "catalog.appscode.com",
      "version": "v1alpha1",
      "name": "pgpoolbindings",
      "kind": "PgpoolBinding",
      "scope": "Namespaced"
    },
    "ui": {
      "editor": {
        "name": "catalogappscodecom-pgpoolbinding-editor",
        "version": "v0.30.0",
        "sourceRef": {
          "apiGroup": "source.toolkit.fluxcd.io",
          "kind": "HelmRepository",
          "name": "appscode-charts-oci"
        }
      },
      "enforceQuota": false
    },
    "icons": [
      {
        "src": "https://cdn.appscode.com/k8s/icons/catalog.appscode.com/pgpoolbindings.svg",
        "type": "image/svg+xml"
      },
      {
        "src": "https://cdn.appscode.com/k8s/icons/catalog.appscode.com/pgpoolbindings.png",
        "type": "image/png"
      }
    ]
  }
}
